#!/bin/sh
# Simple script for invoking Atomic
DIR="$( cd "$( dirname "$0" )" && pwd )"
java -cp ${DIR}/atomic.jar Atomic "org.apache.derby.jdbc.ClientDriver" "jdbc:derby://localhost:1527/Test;create=true" 
